# ==========================================
# TinyServer 控制面板
# ==========================================

# 1. 数据库配置
db_host=tiny_mysql
db_port=3306
db_user=webuser
db_pwd=123456
db_name=tiny_server

# 2. Redis 配置
redis_host=tiny_redis
redis_port=6379

# 3. 日志雷达配置 (0:DEBUG, 1:INFO, 2:WARN, 3:ERROR)
# 压测时改成 3
log_level=3